# 禁用读取 /etc/resolv.conf
no-resolv
# 设置默认的上游 DNS
server=1.0.0.1 # 主 DNS，Cloudfare Public DNS
server=8.8.8.8 # 备用 DNS，Google Public DNS
cache-size=2048
local-ttl=60
listen-address=127.0.0.1
# Disney DNS解锁
server=/dmm.co.jp/166.0.199.207
server=/dmm.com/166.0.199.207
